version: '3.8'


services:
  bot:
    build:
      context: . 
      dockerfile: Dockerfile
    working_dir: /app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped